GET http://localhost:3000/usuario

### para criar o proximo botão
POST  http://localhost:3000/usuario
Content-Type:  application/json

{
    "nome": "Teste2",
    "email": "teste2@gmail.com",
    "senha": "123456"
}

###
GET http://localhost:3000/usuario/1

###
DELETE  http://localhost:3000/usuario/2

###
PATCH http://localhost:3000/usuario/1
Content-Type:  application/json

{
    "nome": "Teste Teste",
    "email": "teste@gmail.com",
    "senha": "12345678"
}